spring:
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always #打印日志彩色
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB #上传文件大小和请求大小
  datasource:
    username: rpan
    password: XmYkNT5hMMQcyBbi
    url: jdbc:mysql://113.44.201.198:13306/rpan?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
#  redis:
#    database: 1
#    host: 127.0.0.1
#  application:
#    name: r-pan-server
#  output:
#    ansi:
#      enabled: always
#  mvc:
#    servlet:
#      load-on-startup: 1
#  servlet:
#    multipart:
#      max-file-size: 3072MB
#      max-request-size: 3072MB

#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#        exclude: env,beans
#
#swagger2:
#  show: true
#  group-name: ${spring.application.name}
#  base-package: com.why.pan
#  title: r-pan-server docs
#  description: r-pan-server docs
#  terms-of-service-url: http://127.0.0.1:${server.port}
#  contact-name: why
#  contact-url: https://blog.why.com
#  contact-email: why@126.com
#  version: 1.0
#
#logging:
#  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
#  level:
#    root: INFO
#
##com:
##  imooc:
##    pan:
##      storage:
##        engine:
##          oss:
##            bucket-name: pan-imooc-test-1
##            endpoint: oss-cn-beijing.aliyuncs.com
##            access-key-id: LTAI5tJiLByyUfFwWYEXZFvg
##            access-key-secret: Fm5rkdaHCkwaFqOfm6Md21mIi26cjv
##            auto-create-bucket: true
##          fdfs:
##            connect-timeout: 600
##            tracker-list:
##              - 39.98.37.93:22122
##            group: group1
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans #健康管理的接口
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: xyz.xlls.rpan
  title: r-pan-server docs
  description: r-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: xkk
  contact-url: https://blog.xlls.xyz
  contact-email: zhangdehenshuaiyy.outlook.com
  version: 1.0